# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "ntalbs' stuff"

# subtitle:
description: 내 이 세상 도처에서 쉴 곳을 찾아보았으나, 마침내 찾아낸, 컴퓨터가 있는 구석방보다 나은 곳은 없더라.
author: ntalbs
email: ntalbsko@gmail.com
language: ko
timezone: Europe/London

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://ntalbs.github.io
root: /
permalink: :year/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
skip_renderer:
- '**/*.js'

# Writing
new_post_name: :year/:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number:
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname: ntalbs-stuff

# Extensions
## Plugins: http://hexo.io/plugins/
html_minifier:
  enable: true
  exclude:

css_minifier:
  enable: true
  exclude:
    - "*.min.css"

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - "*.min.js"

image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

## Themes: http://hexo.io/themes/
theme: simplet
#exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Stylus
stylus:
  compress: true

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: https://github.com/ntalbs/ntalbs.github.io.git

# Sitemap Generation
sitemap:
  path: sitemap.xml

# Redirect from old URLs
alias:
  2008/10/24/dbms-job/: 2008/dbms-job/
  2008/10/27/add-column-and-default-value/: 2008/add-column-and-default-value/
  2008/10/27/direct-load-and-index/: 2008/direct-load-and-index/
  2008/10/27/direct-path-load/: 2008/direct-path-load/
  2008/10/28/data-type/: 2008/data-type/
  2008/10/28/partition-by-timestamp/: 2008/partition-by-timestamp/
  2008/10/28/storing-dates/: 2008/storing-dates/
  2008/10/29/set-timing/: 2008/set-timing/
  2008/10/30/disabling-xdb-in-oracle/: 2008/disabling-xdb-in-oracle/
  2008/10/31/long-move-ts/: 2008/long-move-ts/
  2008/11/01/select-shell/: 2008/select-shell/
  2008/11/01/sqlplus-ampersand/: 2008/sqlplus-ampersand/
  2008/11/03/oracle-factorial/: 2008/oracle-factorial/
  2008/11/08/extract-ddl/: 2008/extract-ddl/
  2008/11/17/sizing-table/: 2008/sizing-table/
  2008/11/18/sizing-index/: 2008/sizing-index/
  2008/12/04/dbms-metadata/: 2008/dbms-metadata/
  2009/02/16/db-performance/: 2009/db-performance/
  2009/04/10/credit-card/: 2009/credit-card/
  2009/06/25/625/: 2009/625/
  2009/07/13/password/: 2009/password/
  2009/08/20/login-sql/: 2009/login-sql/
  2009/11/11/create-db/: 2009/create-db/
  2010/02/04/id/: 2010/id-2/
  2010/05/16/duplicated-codes/: 2010/duplicated-codes/
  2010/07/09/postgresql-date/: 2010/postgresql-date/
  2010/07/27/sql-loader/: 2010/sql-loader/
  2010/08/01/export-compress/: 2010/export-compress/
  2010/08/02/uncompress-import/: 2010/uncompress-import/
  2010/08/13/meaning-of-default/: 2010/meaning-of-default/
  2010/09/05/google-main-page/: 2010/google-main-page/
  2010/09/06/google-main-page/: 2010/google-main-page/
  2010/11/26/parameter-argument/: 2010/parameter-argument/
  2010/12/14/sql-problem/: 2010/sql-problem/
  2011/04/04/probablity/: 2011/probablity/
  2011/04/13/tricky-xml/: 2011/tricky-xml/
  2011/04/14/tricky-xml/: 2011/tricky-xml/
  2011/06/03/jstestdriver-exclude/: 2011/jstestdriver-exclude/
  2011/08/11/no-such-method-error/: 2011/no-such-method-error/
  2011/08/23/final-local-var/: 2011/final-local-var/
  2014/04/08/clojure-fallacy/: 2014/clojure-fallacy/
  2014/04/09/word-lorem/: 2014/word-lorem/
  2014/04/16/numbering-multi-level-list/: 2014/numbering-multi-level-list/
  2014/05/08/lombok/: 2014/lombok/
  2014/05/22/ignoring-ie8/: 2014/ignoring-ie8/
  2014/07/25/newtons-method/: 2014/newtons-method/
  2014/07/28/implementing-sin-x/: 2014/implementing-sin-x/
  2014/08/05/jps/: 2014/jps/
  2014/08/20/dystopian-future/: 2014/dystopian-future/
  2014/08/21/html-str-in-js/: 2014/html-str-in-js/
  2014/08/22/html-str-in-js/: 2014/html-str-in-js/
  2014/09/11/dba-story-1/: 2014/dba-story-1/
  2014/09/12/dba-story-1/: 2014/dba-story-1/
  2014/09/14/dba-story-2/: 2014/dba-story-2/
  2014/10/01/dba-story-4/: 2014/dba-story-4/
  2014/10/16/hexo-hljs/: 2014/hexo-hljs/
  2014/11/11/quicksort/: 2014/quicksort/
  2014/11/12/mysql-row-generator/: 2014/mysql-row-generator/
  2014/12/05/regexp-counter/: 2014/regexp-counter/
  2014/12/15/multiple-jdk-on-macosx/: 2014/multiple-jdk-on-macosx/
  2015/01/01/project-euler-001/: 2015/project-euler-001/
  2015/01/05/cigaret-cutter/: 2015/cigaret-cutter/
  2015/01/09/sql-transpose/: 2015/sql-transpose/
  2015/01/11/changing-shortcut-in-macosx/: 2015/changing-shortcut-in-macosx/
  2015/02/24/project-euler-008/: 2015/project-euler-008/
  2015/02/26/emacs-removing-blank-lines/: 2015/emacs-removing-blank-lines/
  2015/03/17/project-euler-012/: 2015/project-euler-012/
  2015/04/07/statement-expresssion/: 2015/statement-expresssion/
  2015/04/28/stop-using-tail/: 2015/stop-using-tail/
  2015/05/11/project-euler-018/: 2015/project-euler-018/
  2015/05/14/project-euler-019/: 2015/project-euler-019/
  2015/06/10/if-cond-condp-case/: 2015/if-cond-condp-case/
  2015/06/11/editor-hierarchy/: 2015/editor-hierarchy/
  2015/07/28/editor-ime/: 2015/editor-ime/
  2015/09/22/why-emacs/: 2015/why-emacs/
  2015/09/24/project-euler-030/: 2015/project-euler-030/
  2015/10/26/project-euler-042/: 2015/project-euler-042/
  2015/11/02/project-euler-044/: 2015/project-euler-044/
  2015/12/28/amazon-1/: 2015/amazon-1/
